########################################################################
# WEBSITE https://flowork.cloud
# File NAME : C:\FLOWORK\cloudflared\config.yml total lines 12 
########################################################################

tunnel: flowork-selfhost
credentials-file: C:\FLOWORK\cloudflared\credentials.json
ingress:
  - hostname: socket.flowork.cloud
    service: http://flowork_gateway:8000
  - service: http_status:404
